### ISSUE TITLE
AAS GUI fails when running with Traefik

### ISSUE THREAD

**Issue by ipa-big** [eclipse-basyx/basyx-applications#47]
### Environment

Run the following docker-compose file (contains aas-registry, aas-server, aas-db, aas-gui, traefik):

```
version: '3'

services:
  traefik:
    image: traefik:v3.0
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./traefik_config.yml:/etc/traefik/traefik.yml"

  aas-registry:
    image: eclipsebasyx/aas-registry:1.4.0
    depends_on:
      - aas-database
      - aas-server
      - aas-gui
    environment:
      basyxregistry_registry_backend: MongoDB
      basyxmongodb_dbconnectionstring: mongodb://aas-database:27017/
      basyxcontext_accesscontrolalloworigin: "*"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aas-registry.rule=PathPrefix(`/aas-registry/`)"
      - "traefik.http.routers.aas-registry.service=aas-registry"
      - "traefik.http.routers.aas-registry.middlewares=aas-registry"
      - "traefik.http.middlewares.aas-registry.stripprefix.prefixes=/aas-registry"
      - "traefik.http.services.aas-registry.loadbalancer.server.port=4000"
      - "traefik.docker.network=default"
    networks:
      - default

  aas-server:
    image: eclipsebasyx/aas-server:1.4.0
    depends_on:
      - aas-database
    environment:
      basyxaas_registry_path: http://aas-registry:4000/registry/api/v1/registry
      basyxaas_aas_backend: MongoDB
      basyxaas_aas_aasxupload: Enabled
      basyxaas_registry_host: http:///aas-server:4001/aas-server/aasServer
      basyxmongodb_dbconnectionstring: mongodb://aas-database:27017/
      basyxcontext_accesscontrolalloworigin: "*"
      waiting_for: '[{"host":"aas-registry","port":"4000"}]'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aas-server.rule=PathPrefix(`/aas-server/`)"
      - "traefik.http.routers.aas-server.service=aas-server"
      - "traefik.http.routers.aas-server.middlewares=aas-server"
      - "traefik.http.middlewares.aas-server.stripprefix.prefixes=/aas-server"
      - "traefik.http.services.aas-server.loadbalancer.server.port=4001"
      - "traefik.docker.network=default"
    networks:
      - default

  aas-database:
    image: mongo:latest
    volumes:
      - "aas-database:/data/db"

  aas-gui:
    image: eclipsebasyx/aas-gui:v230703
    environment:
      VITE_BASE_PATH: "/aas-gui"
      VITE_REGISTRY_PATH: "http:///localhost/aas-registry/registry"
      VITE_AAS_SERVER_PATH: "http:///localhost/aas-server/aasServer"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aas-gui.rule=PathPrefix(`/aas-gui/`)"
      - "traefik.http.routers.aas-gui.service=aas-gui"
#      - "traefik.http.routers.aas-gui.middlewares=aas-gui"
#      - "traefik.http.middlewares.aas-gui.stripprefix.prefixes=/aas-gui"
      - "traefik.http.services.aas-gui.loadbalancer.server.port=3000"
      - "traefik.docker.network=default"
    networks:
      - default

networks:
  default:

volumes:
  aas-database:
```

with traefik_config.yml:

```
global:
  checkNewVersion: false
  sendAnonymousUsage: false
entryPoints:
  web:
    address: :80

  websecure:
    address: :443
api:
  insecure: true
  dashboard: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
```

### Expected behavior

When opening http://localhost/aas-gui aas-gui should be visible

### What really happens

When opening http://localhost/aas-gui aas-gui is not loading and console is showing error messages:

![image](https://github.com/eclipse-basyx/basyx-applications/assets/18415320/9fa6c600-f558-4baf-bb07-2e8416df2b62)

![image](https://github.com/eclipse-basyx/basyx-applications/assets/18415320/e5983b3d-0754-4e75-8d0d-c2305a39a190)

### Possible reason why it fails

AAS GUI tries to load /src/main.ts and /@vite/client from http://localhost and not from http://localhost/aas-gui and therefore requests for those files do not reach aas-gui because traefik has no routing rules for "/src" and "/@vite" path. 

Env variable VITE_BASE_PATH=/aas-gui does not fix the problem.

### Workaround (for now)

Add additional traefik routing routes, so requests to "/src", "/@vite", "/node_modules" and "/@id" are also forwarded to aas-gui container:

```
labels:
        - "traefik.http.routers.aas-gui.rule=PathPrefix(`/aas-gui/`) || PathPrefix(`/@vite/client`) || PathPrefix(`/src`) || PathPrefix(`/node_modules`) || PathPrefix(`/@id`)"
```

Opening http://localhost/aas-gui/ works with workaround:

![image](https://github.com/eclipse-basyx/basyx-applications/assets/18415320/146af116-2803-43ee-a894-fd1cf00452ab)

#### Host/Path rewrite

AAS GUI rewrites hostname/path in address bar of browser (maybe this is part of the problem):

this: 

![image](https://github.com/eclipse-basyx/basyx-applications/assets/18415320/49b228c6-2305-46c7-bb76-3ef7fcb371e5)

turns into this:

![image](https://github.com/eclipse-basyx/basyx-applications/assets/18415320/fe43cea8-c462-45d7-b5b5-737bb24cd50c)

#### VITE_BASE_PATH behaviour

Looks like env var VITE_BASE_PATH works for some parts of the App but not all. Loading the logo does not work when setting VITE_BASE_PATH=/aas-gui and do not strip path prefix via traefik. 

![image](https://github.com/eclipse-basyx/basyx-applications/assets/18415320/fedfa2d8-4d78-4584-b5d3-11af589062ff)
![image](https://github.com/eclipse-basyx/basyx-applications/assets/18415320/6b801d1d-d8c9-4f51-9e4b-acf02c900d66)

When enabeling stripping path prefix in traefik, loading the logo works:

```
- "traefik.http.routers.aas-gui.middlewares=aas-gui"
- "traefik.http.middlewares.aas-gui.stripprefix.prefixes=/aas-gui"
```
